#!/usr/bin/env bash

# Set the name of the private key file
key_name="school"

# Generate the key pair with 4096 bits and passphrase protection
ssh-keygen -t rsa -b 4096 -f ~/.ssh/"$key_name" -N "betty" >/dev/null << EOF
y
EOF

# Print the success message
echo "Your identification has been saved in $key_name."
echo "Your public key has been saved in $key_name.pub."

